/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RiskCenterRouteImport } from './routes/risk-center'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as IdentityExplorerRouteImport } from './routes/identity-explorer'
import { Route as FindingsRouteImport } from './routes/findings'
import { Route as AiCopilotRouteImport } from './routes/ai-copilot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdentityIdRouteImport } from './routes/identity.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskCenterRoute = RiskCenterRouteImport.update({
  id: '/risk-center',
  path: '/risk-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityExplorerRoute = IdentityExplorerRouteImport.update({
  id: '/identity-explorer',
  path: '/identity-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCopilotRoute = AiCopilotRouteImport.update({
  id: '/ai-copilot',
  path: '/ai-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityIdRoute = IdentityIdRouteImport.update({
  id: '/identity/$id',
  path: '/identity/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/findings': typeof FindingsRoute
  '/identity-explorer': typeof IdentityExplorerRoute
  '/reports': typeof ReportsRoute
  '/risk-center': typeof RiskCenterRoute
  '/settings': typeof SettingsRoute
  '/identity/$id': typeof IdentityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/findings': typeof FindingsRoute
  '/identity-explorer': typeof IdentityExplorerRoute
  '/reports': typeof ReportsRoute
  '/risk-center': typeof RiskCenterRoute
  '/settings': typeof SettingsRoute
  '/identity/$id': typeof IdentityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/findings': typeof FindingsRoute
  '/identity-explorer': typeof IdentityExplorerRoute
  '/reports': typeof ReportsRoute
  '/risk-center': typeof RiskCenterRoute
  '/settings': typeof SettingsRoute
  '/identity/$id': typeof IdentityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-copilot'
    | '/findings'
    | '/identity-explorer'
    | '/reports'
    | '/risk-center'
    | '/settings'
    | '/identity/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-copilot'
    | '/findings'
    | '/identity-explorer'
    | '/reports'
    | '/risk-center'
    | '/settings'
    | '/identity/$id'
  id:
    | '__root__'
    | '/'
    | '/ai-copilot'
    | '/findings'
    | '/identity-explorer'
    | '/reports'
    | '/risk-center'
    | '/settings'
    | '/identity/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiCopilotRoute: typeof AiCopilotRoute
  FindingsRoute: typeof FindingsRoute
  IdentityExplorerRoute: typeof IdentityExplorerRoute
  ReportsRoute: typeof ReportsRoute
  RiskCenterRoute: typeof RiskCenterRoute
  SettingsRoute: typeof SettingsRoute
  IdentityIdRoute: typeof IdentityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-center': {
      id: '/risk-center'
      path: '/risk-center'
      fullPath: '/risk-center'
      preLoaderRoute: typeof RiskCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity-explorer': {
      id: '/identity-explorer'
      path: '/identity-explorer'
      fullPath: '/identity-explorer'
      preLoaderRoute: typeof IdentityExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings': {
      id: '/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-copilot': {
      id: '/ai-copilot'
      path: '/ai-copilot'
      fullPath: '/ai-copilot'
      preLoaderRoute: typeof AiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity/$id': {
      id: '/identity/$id'
      path: '/identity/$id'
      fullPath: '/identity/$id'
      preLoaderRoute: typeof IdentityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiCopilotRoute: AiCopilotRoute,
  FindingsRoute: FindingsRoute,
  IdentityExplorerRoute: IdentityExplorerRoute,
  ReportsRoute: ReportsRoute,
  RiskCenterRoute: RiskCenterRoute,
  SettingsRoute: SettingsRoute,
  IdentityIdRoute: IdentityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
